[package]
name = "tictactoe2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
text-tables = "0.3.1"
tokio = {version = "1.36.0" , features = ["full"]}

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
